version: 2
updates:
- package-ecosystem: "npm"
  directory: "/"
  schedule:
    interval: "cron"
    cronjob: "0 8 * * 2,4"
  open-pull-requests-limit: 10
  groups:
    eslint:
      patterns:
        - "eslint"
        - "@eslint/js"
